### ISSUE TITLE
Can't upgrade Strapi because of a sharp error

### ISSUE THREAD

**Issue by VivianSolide** [YegorShtonda/strapi-provider-upload-aws-s3-resizing-and-optimisation#13]
Hi there!

I'm not able to bump my Strapi from 3.5.4 to 3.6.3

I get this error:
```
(sharp:468549): GLib-GObject-WARNING **: 12:51:17.371: cannot register existing type 'gchar'
**
GLib-GObject:ERROR:../gobject/gvaluetypes.c:454:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
Bail out! GLib-GObject:ERROR:../gobject/gvaluetypes.c:454:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
```

Is there a way to run the update without breaking anything?

**Comment by YegorShtonda** [comment]
I don't know, maybe this is a problem on the sharp side. If you fix this error, please make a pull request. I no support this repository and I already badly remember the code that wrote.

You may be interested in my current way of compressing images in fly
https://github.com/YegorShtonda/strapi-plugin-img

**Comment by FredWahlqvistDrop** [comment]
It looks like there is a issue with Sharp, need to update the dependency version..
https://github.com/lovell/sharp/issues/2356

Found another lib that supports similar functionality, suggest to either support this lib or decommission it in support of 
https://github.com/garretua/strapi-provider-upload-aws-s3-enhanced

(ps its a nice plugin in general)
