### ISSUE TITLE
webp images are not getting store in database.

### ISSUE THREAD

**Issue by nitin2711** [YegorShtonda/strapi-provider-upload-aws-s3-resizing-and-optimisation#8]
i am using this plugin and want to access webp images in html. but it is not store in database as large, medium, small... etc sizes are stored.

**Comment by YegorShtonda** [comment]
This provider in terms of architecture is not a very good solution but simple. It is not possible to write additional image data to the database at the provider stage.

I will solve this problem with the help of my new plugin, I will write here when I publish
